### ISSUE TITLE
Path issues

### ISSUE THREAD

**Issue by tasinttttttt** [citymont/symetrie#1]
Hey there! wanted to try symetrie but it seems there's an issue involving `__DIR__` used for urls...

This method is only good if used at the root of a webserver. Doesn't work on `localhost` (or I don't know how to).

Maybe declaring a global `PATH` variable for flexibility, and then use it with `$_SERVER['SERVER_NAME']` ?

**Comment by citymont** [comment]
Hey,
**DIR** is perfect for file but it only exists with PHP >= 5.3 .
I'm working with localhost and I have no issue.
