### ISSUE TITLE
A Reflected XSS vulnerability in page.php

### ISSUE THREAD

**Issue by jgj212** [citymont/symetrie#3]
Hello:
I have find a Reflected XSS vulnerability.

The vulnerability exists due to insufficient filtration of user-supplied data in "model" HTTP parameter that will be passed to " symetrie-master/app/commands/page.php". The infected source code is line 18, there is no protection on $_GET['model'], if it contains evil js code, line 52 will trigger untrusted code to be executed on the browser side.
![1](https://cloud.githubusercontent.com/assets/1484292/24279172/2be5a978-1083-11e7-80de-3de6d1dc4227.png)
 

So if a attacker construct a special url as follow and send it to a victim, when the victim click the url, the code which is contained in the url will be executed on the victim's browser side to do some evil.
http://your-web-root/ symetrie-master/app/commands/page.php?model="><script>alert(1);</script><"

The follow scrrenshot is the result to click the upper url ( win7 sp1 x64 + firefox 51.0.1 32bit ):
![2](https://cloud.githubusercontent.com/assets/1484292/24279356/4b5ef592-1084-11e7-91be-066749d63576.png)

Discoverer: ADLab of Venustech

**Comment by citymont** [comment]
obvious ... fixed now 
9bb365910ab1f2537e50eec705ecbe40a8f658f9
